spring:
  data:
    mongodb:
      host: 47.97.101.159
      username: user
      password: password
      database: piggymetrics
      port: 27017
  rabbitmq:
    host: 47.111.180.200
    username: guest
    password: guest

server:
  servlet:
    context-path: /uaa
  port: 5000
