security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 47.97.101.159
      username: user
      password: password
      database: piggymetrics
      port: 27017
  rabbitmq:
    host: 47.111.180.200
    username: guest
    password: guest

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io